# Site settings
title: "Encarna Isabel Gómez Campoy"
description: "Formada en ingeniería técnica de Obras Públicas, dedicada a la educación secundaria"

# Resume settings
resume_name: Encarna Isabel Gómez Campoy
resume_title: Profesora de secundaria
resume_header_intro: "Formada en ingeniería técnica de Obras Públicas, dedicada a la educación secundaria. Profesora de tecnología"
resume_social:
  github: https://github.com/encarnaisabel
  twitter: https://twitter.com/encarnaisabel
  linkedin: https://es.linkedin.com/in/encarna-isabel-g%C3%B3mez-campoy-611014a5

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
